"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { getPhase3Client } from "@/lib/phase3";
export default function ResetPasswordPage() {
  const client = useMemo(() => getPhase3Client(), []); const [sessionReady, setSessionReady] = useState(false); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [complete, setComplete] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const p = new URLSearchParams(location.hash.slice(1)); const accessToken = p.get("access_token"), refreshToken = p.get("refresh_token"); if (!accessToken || !refreshToken) return; history.replaceState(null, "", location.pathname); client.establishRecoverySession(accessToken, refreshToken).then(() => setSessionReady(true)).catch(() => setError("This recovery link is invalid or expired. Request a new one.")); }, [client]);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); if (!sessionReady) return setError("This recovery link is invalid or expired. Request a new one."); if (password !== confirm) return setError("Enter the same password in both fields."); if (password.length < 12 || !/[a-z]/.test(password) || !/[A-Z]/.test(password) || !/\d/.test(password) || !/[^A-Za-z0-9]/.test(password)) return setError("Use at least 12 characters with uppercase, lowercase, a number, and a special character."); try { await client.resetPassword(password); setComplete(true); } catch { setError("Your password could not be updated. Request a new recovery link and try again."); } }
  return <div className="page shell auth-page"><section className="auth-card"><p className="eyebrow">Secure recovery</p><h1>Choose a new password.</h1>{complete ? <><p className="boundary-note">Your password has been updated.</p><Link className="button primary" href="/login">Continue to sign in</Link></> : <form className="auth-form" onSubmit={submit}><label htmlFor="password">New password</label><input id="password" type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required /><p className="form-hint">At least 12 characters, including uppercase, lowercase, a number, and a special character.</p><label htmlFor="confirm">Confirm new password</label><input id="confirm" type="password" autoComplete="new-password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required />{error && <p className="form-error" role="alert">{error}</p>}<button className="button primary">Update password</button></form>}<p className="auth-secondary"><Link href="/auth/forgot-password">Request a new link</Link></p></section></div>;
}
