import type { Profile } from "./types";

// All member data is fictional sample content for the discovery prototype.
export const profiles: Profile[] = [
  {
    slug: "cascade-canna",
    name: "Cascade Canna Co.",
    role: "Brand",
    location: "Portland, Oregon",
    description: "Small-batch edibles built for dependable retail velocity.",
    specialties: ["Edibles", "Wholesale", "Woman-owned"],
    verified: true,
    initials: "CC",
    imageSrc: "/bridge-editorial/profile-cascade-canna.webp",
    imageAlt: "Cascade Canna team preparing small-batch edibles for wholesale partners",
    serving: "Serving Oregon and Washington",
    about:
      "Cascade creates small-batch edibles for independent dispensaries that want dependable sell-through, transparent ingredients, and responsive wholesale support.",
    lookingFor: ["Retail partnerships", "Regional distributors", "Event collaboration"],
    products: ["Edibles", "Pre rolls", "Seasonal wholesale releases"],
    marketSignal: "Pacific Northwest buyers are planning fall education and shelf reset calendars.",
    channels: ["Instagram", "LinkedIn", "Leafly"],
    recentActivity: [
      { title: "Published fall wholesale calendar", meta: "Promotion · Verified retailers" },
      { title: "Added Washington availability", meta: "Profile update · 2 days ago" },
    ],
    announcement: {
      title: "Now accepting Washington retail partners",
      body: "Our summer wholesale calendar is open through August 31.",
    },
  },
  {
    slug: "harbor-dispensary",
    name: "Harbor Dispensary",
    role: "Dispensary",
    location: "Baltimore, Maryland",
    description: "Community-first dispensary seeking premium regional partners.",
    specialties: ["Retail", "Education", "Maryland"],
    verified: true,
    initials: "HD",
    imageSrc: "/bridge-editorial/profile-harbor-dispensary.webp",
    imageAlt: "Harbor Dispensary buyer welcoming a regional cannabis partner",
    serving: "Serving the Baltimore metro area",
    about:
      "Harbor pairs a curated shelf with patient education, and looks for brands that can support in-store training and consistent regional supply.",
    lookingFor: ["Premium brands", "Educational partners", "Local events"],
    products: ["Flower", "Edibles", "Pre rolls", "Wellness"],
    marketSignal: "Maryland buyers are planning education led fall promotions and regional brand events.",
    menuItems: ["Maryland grown flower", "Low dose edibles", "Solventless concentrates", "Pre roll multipacks"],
    orderProvider: "Dutchie connection",
    channels: ["Instagram", "Facebook", "LinkedIn", "Leafly"],
    recentActivity: [
      { title: "Opened fall shelf reset requests", meta: "Buying signal · 3 hours ago" },
      { title: "Scheduled community education night", meta: "Event · This week" },
    ],
    announcement: {
      title: "Fall shelf reset planning has started",
      body: "Submitting brands should share wholesale menus by September 15.",
    },
  },
  {
    slug: "northstar-sales",
    name: "Northstar Sales Group",
    role: "Sales rep",
    location: "Chicago, Illinois",
    description: "Multi-state representation for emerging cannabis operators.",
    specialties: ["Distribution", "B2B", "Midwest"],
    verified: false,
    initials: "NS",
    imageSrc: "/bridge-editorial/profile-northstar-sales.webp",
    imageAlt: "Northstar Sales Group mapping cannabis retail territories",
    serving: "Serving Illinois, Michigan, and Missouri",
    about:
      "Northstar represents emerging brands across the Midwest with an emphasis on route density, retail education, and honest sell-through reporting.",
    lookingFor: ["Brands entering the Midwest", "Territory expansion", "Retail introductions"],
    products: ["Territory representation", "Retail introductions", "Sell through reporting"],
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Requested Michigan retail introductions", meta: "Signal · Yesterday" }],
  },
  {
    slug: "mosaic-market",
    name: "Mosaic Market",
    role: "Retailer",
    location: "Phoenix, Arizona",
    description: "A curated retail network focused on trusted customer experiences.",
    specialties: ["Retail", "Multi-location", "Arizona"],
    verified: true,
    initials: "MM",
    imageSrc: "/bridge-editorial/profile-mosaic-market.webp",
    imageAlt: "Mosaic Market team merchandising a curated dispensary shelf",
    serving: "Serving greater Phoenix from three locations",
    about:
      "Mosaic operates three storefronts with a shared buying team and looks for brands and representatives that can service multiple locations reliably.",
    lookingFor: ["Multi-store supply", "Category exclusives", "Merchandising support"],
  },
  {
    slug: "greenline-goods",
    name: "Greenline Goods",
    role: "Brand",
    location: "Trenton, New Jersey",
    description: "Modern wellness products with transparent sourcing.",
    specialties: ["Wellness", "CBD", "New Jersey"],
    verified: true,
    initials: "GG",
    imageSrc: "/bridge-editorial/profile-greenline-goods.webp",
    imageAlt: "Greenline Goods wellness tinctures in a modern product studio",
    serving: "Serving New Jersey and Pennsylvania",
    about:
      "Greenline builds wellness-focused products with published sourcing and third-party testing, aimed at retailers who lead with education.",
    lookingFor: ["East-coast retailers", "Distribution partners", "Wellness collaborations"],
    products: ["Tinctures", "Topicals", "CBD wellness"],
    channels: ["Instagram", "LinkedIn"],
    recentActivity: [{ title: "Released a lab verified tincture line", meta: "Product launch · This week" }],
    announcement: {
      title: "New lab-verified tincture line",
      body: "Wholesale samples are available for verified retail partners.",
    },
  },
  {
    slug: "presque-isle-wellness",
    name: "Presque Isle Wellness",
    role: "Dispensary",
    location: "Erie, Pennsylvania",
    description: "Lakeside dispensary pairing careful sourcing with patient education.",
    specialties: ["Retail", "Patient education", "Pennsylvania"],
    verified: true,
    initials: "PI",
    imageSrc: "/bridge-editorial/profile-presque-isle-wellness.webp",
    imageAlt: "Presque Isle Wellness team reviewing patient education materials",
    serving: "Serving Erie and northwest Pennsylvania",
    about:
      "Presque Isle Wellness serves the Erie lakefront with a tightly curated menu and looks for Pennsylvania brands that can support consistent supply and staff training.",
    lookingFor: ["Pennsylvania brands", "Wholesale partners", "Community events"],
    announcement: {
      title: "Expanding the Pennsylvania-grown shelf",
      body: "Meeting new in-state brands through August for the fall reset.",
    },
  },
  {
    slug: "steel-city-botanicals",
    name: "Steel City Botanicals",
    role: "Brand",
    location: "Pittsburgh, Pennsylvania",
    description: "Concentrates and vapes built for consistent regional wholesale.",
    specialties: ["Concentrates", "Wholesale", "Pennsylvania"],
    verified: true,
    initials: "SB",
    imageSrc: "/bridge-editorial/profile-steel-city-botanicals.webp",
    imageAlt: "Steel City Botanicals preparing compliant concentrate production",
    serving: "Serving Pennsylvania and Ohio",
    about:
      "Steel City produces small-batch concentrates with published testing and looks for retail partners across Pennsylvania and Ohio that value dependable restock schedules.",
    lookingFor: ["Retail partnerships", "Regional distributors", "Budtender training"],
  },
  {
    slug: "front-range-reps",
    name: "Front Range Reps",
    role: "Sales rep",
    location: "Denver, Colorado",
    description: "Mountain-west representation for craft brands entering new markets.",
    specialties: ["B2B", "Territory management", "Mountain West"],
    verified: false,
    initials: "FR",
    imageSrc: "/bridge-editorial/profile-front-range-reps.webp",
    imageAlt: "Front Range Reps planning a mountain-west territory launch",
    serving: "Serving Colorado and New Mexico",
    about:
      "Front Range represents craft brands across the mountain west with an emphasis on route coverage, honest sell-through data, and long-term retail relationships.",
    lookingFor: ["Craft brands", "New territory launches", "Retail introductions"],
  },
  {
    slug: "motor-city-supply",
    name: "Motor City Supply Co.",
    role: "Retailer",
    location: "Detroit, Michigan",
    description: "Two-location retailer with a shared buying team and steady velocity.",
    specialties: ["Retail", "Multi-location", "Michigan"],
    verified: true,
    initials: "MC",
    imageSrc: "/bridge-editorial/profile-motor-city-supply.webp",
    imageAlt: "Motor City Supply buyers planning product assortment and restocks",
    serving: "Serving metro Detroit from two locations",
    about:
      "Motor City Supply runs two storefronts with one buying team and looks for brands and reps that can service both locations on a single schedule.",
    lookingFor: ["Multi-store supply", "Michigan brands", "Merchandising support"],
  },
  {
    slug: "union-street",
    name: "Union Street Collective",
    role: "Dispensary",
    location: "Boston, Massachusetts",
    description: "Independent operator building a stronger local supply chain.",
    specialties: ["Retail", "Local", "Massachusetts"],
    verified: false,
    initials: "US",
    imageSrc: "/bridge-editorial/profile-union-street.webp",
    imageAlt: "Union Street Collective greeting a local supply partner",
    serving: "Serving Boston and the North Shore",
    about:
      "Union Street prioritizes Massachusetts-grown supply and partners with local operators who value shorter, more transparent supply chains.",
    lookingFor: ["Local cultivators", "Craft brands", "Community events"],
  },
  {
    slug: "golden-state-genetics",
    name: "Golden State Genetics",
    role: "Cultivator",
    location: "Santa Rosa, California",
    description: "A cultivation and genetics partner sharing new strain and production signals nationwide.",
    specialties: ["Cultivation", "Genetics", "California"],
    verified: true,
    initials: "GS",
    imageSrc: "/bridge-editorial/profile-golden-state-genetics.webp",
    imageAlt: "Golden State Genetics team selecting healthy plants in a licensed facility",
    serving: "Serving licensed California manufacturers and multi-state operators",
    about: "Golden State develops stable genetics and production programs for licensed operators that want earlier visibility into emerging cultivars and cultivation practices.",
    lookingFor: ["Licensed manufacturers", "Research partners", "Multi-state operators"],
    products: ["Genetics", "Cultivation consulting", "Clone programs"],
    marketSignal: "California operators are prioritizing dependable genetics and production efficiency over novelty alone.",
    channels: ["Instagram", "LinkedIn"],
    recentActivity: [{ title: "Shared a new cultivar availability signal", meta: "California · Today" }],
  },
  {
    slug: "great-lakes-analytics",
    name: "Great Lakes Analytics",
    role: "Lab",
    location: "Ann Arbor, Michigan",
    description: "Independent cannabis testing and quality intelligence for licensed operators.",
    specialties: ["Testing", "Compliance", "Michigan"],
    verified: true,
    initials: "GL",
    imageSrc: "/bridge-editorial/profile-great-lakes-analytics.webp",
    imageAlt: "Great Lakes Analytics technician working with precision testing instruments",
    serving: "Serving licensed Michigan cultivators, manufacturers, and retailers",
    about: "Great Lakes supports licensed operators with potency, contaminant, stability, and process testing while keeping current laboratory contacts visible to verified partners.",
    lookingFor: ["Cultivators", "Manufacturers", "Quality teams"],
    products: ["Potency testing", "Contaminant screening", "Stability programs"],
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Published updated sample intake windows", meta: "Operations · Today" }],
  },
  {
    slug: "purple-route-logistics",
    name: "Purple Route Logistics",
    role: "Transport",
    location: "Lansing, Michigan",
    description: "Secure licensed transport coordinating retail and wholesale routes.",
    specialties: ["Transport", "Route planning", "Michigan"],
    verified: true,
    initials: "PR",
    imageSrc: "/bridge-editorial/profile-purple-route-logistics.webp",
    imageAlt: "Purple Route Logistics team coordinating secure licensed transport",
    serving: "Serving licensed operators throughout Michigan",
    about: "Purple Route coordinates compliant pickup, chain of custody, and delivery schedules for brands, cultivators, laboratories, and retailers.",
    lookingFor: ["Recurring routes", "Multi-location retailers", "Laboratory transfers"],
    products: ["Secure transport", "Route planning", "Chain of custody"],
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Opened two Southwest Michigan route windows", meta: "Logistics · This week" }],
  },
  {
    slug: "canopy-capital-services",
    name: "Canopy Capital Services",
    role: "Bank",
    location: "Denver, Colorado",
    description: "Cannabis aware banking and treasury support for verified operators.",
    specialties: ["Banking", "Treasury", "Colorado"],
    verified: true,
    initials: "CA",
    imageSrc: "/bridge-editorial/profile-canopy-capital-services.webp",
    imageAlt: "Canopy Capital advisor meeting verified cannabis business operators",
    serving: "Serving verified cannabis businesses in seven legal markets",
    about: "Canopy Capital helps licensed operators understand account requirements, cash management, and expansion readiness without publishing private financial information.",
    lookingFor: ["Licensed operators", "Multi-state businesses", "Finance leaders"],
    products: ["Business banking", "Cash management", "Treasury support"],
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Added Colorado expansion office hours", meta: "Service update · Yesterday" }],
  },
  {
    slug: "root-zone-hydro",
    name: "Root Zone Hydro",
    role: "Hydroponics",
    location: "Sacramento, California",
    description: "Controlled environment equipment and cultivation support for licensed facilities.",
    specialties: ["Hydroponics", "Facility systems", "California"],
    verified: true,
    initials: "RZ",
    imageSrc: "/bridge-editorial/profile-root-zone-hydro.webp",
    imageAlt: "Root Zone Hydro specialist calibrating controlled-environment irrigation",
    serving: "Serving licensed cultivation teams across the West",
    about: "Root Zone supplies irrigation, lighting, environmental controls, and facility support for cultivation teams improving consistency and resource efficiency.",
    lookingFor: ["Facility upgrades", "New cultivation builds", "Maintenance partners"],
    products: ["Irrigation", "Lighting", "Environmental controls"],
    channels: ["Instagram", "LinkedIn"],
    recentActivity: [{ title: "Shared a water efficiency field note", meta: "Education · This week" }],
  },
  {
    slug: "evergreen-facility-group",
    name: "Evergreen Facility Group",
    role: "Service",
    location: "Columbus, Ohio",
    description: "HVAC, electrical, and construction coordination for licensed cannabis facilities.",
    specialties: ["HVAC", "Electrical", "Construction"],
    verified: true,
    initials: "EF",
    imageSrc: "/bridge-editorial/profile-evergreen-facility-group.webp",
    imageAlt: "Evergreen Facility Group inspecting electrical and climate systems",
    serving: "Serving cultivation, manufacturing, and retail facilities in Ohio and Pennsylvania",
    about: "Evergreen coordinates vetted HVAC, electrical, construction, and maintenance teams that already understand licensed cannabis environments.",
    lookingFor: ["Facility projects", "Preventive maintenance", "Expansion planning"],
    products: ["HVAC", "Electrical", "Construction", "Preventive maintenance"],
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Opened fall preventive maintenance scheduling", meta: "Service availability · Today" }],
  },
  {
    slug: "lake-effect-manufacturing",
    name: "Lake Effect Manufacturing",
    role: "Manufacturer",
    location: "Grand Rapids, Michigan",
    description: "Licensed cannabis manufacturing for concentrates, vapes, and dependable white label programs.",
    specialties: ["Manufacturing", "Concentrates", "Michigan"],
    verified: true,
    initials: "LE",
    imageSrc: "/bridge-editorial/profile-lake-effect-manufacturing.webp",
    imageAlt: "Lake Effect Manufacturing preparing compliant product production",
    serving: "Serving licensed Michigan brands and retailers",
    about: "Lake Effect helps licensed partners take tested formulations from production planning through compliant packaging, with current operations contacts available to verified Bridge members.",
    lookingFor: ["Brand partners", "Retail introductions", "Packaging suppliers"],
    products: ["Concentrates", "Vape hardware programs", "White label manufacturing", "Compliant packaging"],
    marketSignal: "Michigan buyers are looking for dependable manufacturing capacity and clearer production lead times.",
    channels: ["LinkedIn"],
    recentActivity: [{ title: "Opened fourth quarter production planning", meta: "Manufacturing signal · Today" }],
  },
  {
    slug: "signal-desk-media",
    name: "Signal Desk Media",
    role: "Media",
    location: "New York, New York",
    description: "Independent cannabis reporting, market education, and operator interviews.",
    specialties: ["Industry news", "Education", "Media"],
    verified: true,
    initials: "SD",
    imageSrc: "/bridge-editorial/profile-signal-desk-media.webp",
    imageAlt: "Signal Desk Media recording a cannabis operator interview",
    serving: "Covering legal cannabis markets nationwide",
    about: "Signal Desk publishes operator interviews, market explainers, and practical industry reporting for Bridge members without paid feed placement.",
    lookingFor: ["Operator stories", "Market experts", "Education partners"],
    products: ["Industry reporting", "Interviews", "Market explainers"],
    channels: ["Instagram", "LinkedIn"],
    recentActivity: [{ title: "Published a California to Michigan market explainer", meta: "Industry article · Today" }],
  },
];

export function getProfile(slug: string): Profile | undefined {
  return profiles.find((profile) => profile.slug === slug);
}
