import { HttpPhase3Client } from "./http-client.ts";
import { Phase3Error } from "./types.ts";
import { validateOrganizationId } from "./organizations.ts";
export type EngagementPost = { id: string; profileId: string; type: "news" | "announcement"; title: string; body: string; status: "draft" | "published"; createdAt: string; updatedAt: string };
export type PostInput = Pick<EngagementPost, "type" | "title" | "body" | "status">;
export type Notification = { id: string; type: string; title: string; body: string; createdAt: string; readAt: string | null };
export type PageInfo = { page: number; pageSize: number; total: number; totalPages: number };
export type SavedProfile = { profileId: string; savedAt: string };
function fail(): never { throw new Phase3Error("unavailable", "The activity response could not be read. Try again."); }
function record(value: unknown): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value)) return fail(); return value as Record<string, unknown>; }
function strings(p: Record<string, unknown>, keys: string[]) { if (keys.some((key) => typeof p[key] !== "string")) fail(); }
export function parsePost(value: unknown): EngagementPost { const p = record(value); strings(p, ["id", "profileId", "title", "body", "createdAt", "updatedAt"]); if (!["news", "announcement"].includes(String(p.type)) || !["draft", "published"].includes(String(p.status))) return fail(); try { validateOrganizationId(p.id as string); validateOrganizationId(p.profileId as string); } catch { return fail(); } if (![p.createdAt, p.updatedAt].every((value) => Number.isFinite(Date.parse(value as string)))) return fail(); return p as EngagementPost; }
function parseNotification(value: unknown): Notification { const p = record(value); strings(p, ["id", "type", "title", "body", "createdAt"]); if (p.readAt !== null && typeof p.readAt !== "string") return fail(); try { validateOrganizationId(p.id as string); } catch { return fail(); } if (!Number.isFinite(Date.parse(p.createdAt as string)) || (p.readAt !== null && !Number.isFinite(Date.parse(p.readAt as string)))) return fail(); return p as Notification; }
function parsePage<T>(value: unknown, key: string, parse: (value: unknown) => T): { items: T[]; pagination: PageInfo } { const p = record(value); const pagination = record(p.pagination); if (!Array.isArray(p[key]) || ["page", "pageSize", "total", "totalPages"].some((key) => !Number.isSafeInteger(pagination[key]) || (pagination[key] as number) < (key === "page" || key === "pageSize" ? 1 : 0))) return fail(); return { items: (p[key] as unknown[]).map(parse), pagination: pagination as PageInfo }; }
export function validatePost(input: PostInput) { if (!input.title.trim() || input.title.length > 200 || !input.body.trim() || input.body.length > 10000 || !["news", "announcement"].includes(input.type) || !["draft", "published"].includes(input.status)) throw new Phase3Error("validation", "Enter a title (up to 200 characters), body (up to 10,000 characters), type and status."); return { type: input.type, title: input.title.trim(), body: input.body.trim(), status: input.status }; }
export class EngagementClient extends HttpPhase3Client {
  posts(page = 1, mine = false) { return this.request<unknown>(`/api/v1/engagement/posts${mine ? "/mine" : ""}?page=${page}&pageSize=20`).then((value) => parsePage(value, "posts", parsePost)); }
  savePost(id: string | null, profileId: string, input: PostInput) { if (id) validateOrganizationId(id); validateOrganizationId(profileId); return this.request<unknown>(`/api/v1/engagement/posts${id ? `/${id}` : ""}`, { method: id ? "PATCH" : "POST", body: JSON.stringify({ ...validatePost(input), ...(!id ? { profileId } : {}) }) }).then((value) => parsePost(record(value).post)); }
  saved(page = 1) { return this.request<unknown>(`/api/v1/engagement/saved-profiles?page=${page}&pageSize=20`).then((value) => parsePage(value, "savedProfiles", (row) => { const p = record(row); strings(p, ["profileId", "savedAt"]); try { validateOrganizationId(p.profileId as string); } catch { return fail(); } if (!Number.isFinite(Date.parse(p.savedAt as string))) return fail(); return p as SavedProfile; })); }
  async isSaved(id: string) { validateOrganizationId(id); const value = record(await this.request<unknown>(`/api/v1/engagement/saved-profiles/${id}`)); if (typeof value.saved !== "boolean") return fail(); return value.saved; }
  async setSaved(id: string, saved: boolean) { validateOrganizationId(id); const value = record(await this.request<unknown>(`/api/v1/engagement/saved-profiles/${id}`, { method: saved ? "PUT" : "DELETE" })); if (value.saved !== saved) fail(); return saved; }
  notifications(page = 1) { return this.request<unknown>(`/api/v1/engagement/notifications?page=${page}&pageSize=20`).then((value) => parsePage(value, "notifications", parseNotification)); }
  markRead(id: string) { validateOrganizationId(id); return this.request<unknown>(`/api/v1/engagement/notifications/${id}`, { method: "PATCH", body: JSON.stringify({ read: true }) }).then((value) => parseNotification(record(value).notification)); }
}
